# Generated by Django 5.2 on 2025-05-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_reference'),
        ),
    ]
