# Generated by Django 5.2.1 on 2025-06-09 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commandeclient_total_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PROD', 'Gestion des produits'), ('VENTE', 'Point de vente'), ('CAISSE', 'Caisse enregistreuse'), ('CLIENT', 'Gestion clients'), ('COMD', 'Gestion des commandes'), ('ADMIN', 'Administration'), ('STAT', 'Statistiques et rapports'), ('INVENTAIRE', 'Gestion des inventaires'), ('CONFIG', 'Configuration et paramètres'), ('LOGS', "Logs d'activité")], max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, default='', max_length=30)),
                ('route', models.CharField(default='/', max_length=100)),
                ('roles_autorises', models.CharField(default='admin', help_text='Séparer par des virgules (ex: admin,gestionnaire)', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': "Module d'application",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire de stock'), ('vendeur', 'Vendeur'), ('caissier', 'Caissier')], default='vendeur', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='api.module'),
        ),
        migrations.CreateModel(
            name='RoleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_role', models.CharField(max_length=20)),
                ('new_role', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
