# Generated by Django 5.2.1 on 2025-06-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_module_alter_utilisateur_role_utilisateur_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(choices=[('PRODUCTS', 'Produits'), ('SALES', 'Ventes'), ('CAISSE', 'Caisse'), ('CUSTOMERS', 'Clients'), ('ORDERS', 'Commandes'), ('ADMIN', 'Administration'), ('REPORTS', 'Statistiques'), ('INVENTORY', 'Inventaire'), ('SETTINGS', 'Paramètres'), ('LOGS', 'Logs')], max_length=10, unique=True),
        ),
    ]
