# Generated by Django 5.2.1 on 2025-06-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_module_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='module',
            name='roles_autorises',
        ),
        migrations.AddField(
            model_name='module',
            name='allowed_roles',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='Nom par défaut', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(choices=[('PRODUCTS', 'Produits'), ('SALES', 'Ventes'), ('CAISSE', 'Caisse'), ('CUSTOMERS', 'Clients'), ('ORDERS', 'Commandes'), ('ADMIN', 'Administration'), ('REPORTS', 'Statistiques'), ('INVENTORY', 'Inventaire'), ('SETTINGS', 'Paramètres'), ('LOGS', 'Logs')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
