# Generated by Django 5.2.1 on 2025-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_module_options_remove_module_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='modules',
            field=models.ManyToManyField(blank=True, to='api.module'),
        ),
    ]
