# Generated by Django 5.2.1 on 2025-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_utilisateur_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='allowed_roles',
        ),
        migrations.AddField(
            model_name='module',
            name='llowed_roles',
            field=models.CharField(default='admin,gestionnaire,vendeur,caissier', max_length=200),
        ),
    ]
