# Generated by Django 5.2.1 on 2025-06-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_module_llowed_roles_module_allowed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
    ]
